#!/usr/bin/node

let request = require('request');
request('http://www.google.com', function (error, response, body) {
  console.log('error:', error); // Print the error if one occurred
  // Print the response status code if a response was received
  console.log('statusCode:', response && response.statusCode);
  console.log('body:', body); // Print the HTML for the Google homepage.
});